---
layout: tutorial.jade
---

= Tutorial Introduction

= Introduction

== Target Audience
The anticipated target audience are users with a Java EE background that haven't touched on many of the microservice topics. They are expected to have solid EE expertise throughout common used API’s like JPA, JAX-RS and CDI.

== Guiding Principles
The tutorial is intended to provide guidance throughout the majority of the activities,
to allow for a positive experience. However there we will provide room for adding
your own ideas and experiment with the technologies in use .

We focus on new concepts and technologies that complement Java EE, but
intentionally leave out cloud deployments, continuous integration and other,
related topics due to the conceptual overhead and technical complexity
it would add to the material.

== Learning Outcomes
The goal is to learn about common concepts in a microservice architecture,
the challenges when migration from a monolith to microservices
and practical examples for crafting a solution using WildFly Swarm.

+++
<div class="row">
  <div class="col-md-6">&nbsp;</div>
  <div class="col-md-6">
  <a href="/tutorial/sources" class="btn btn-primary">Source Code<i class="fa fa-chevron-right" aria-hidden="true"></i></a>
  </div>
</div>
+++
