---
layout: tutorial.jade
---

= Tutorial Introduction

= Introduction

This tutorial will introduce you to WildFly Swarm through the migration of a Java EE monolith application
to microservices for parts of the stack. The services will be discoverable, provide failover with Netflix Ribbon and utilize Netflix Hystrix for circuit breaking amongst other things.

=== Target Audience
The target audience are users with a Java EE background that haven't touched on many of the microservice topics. You are expected to have solid Java EE expertise using common API’s like JPA, JAX-RS and CDI.

NOTE: The section on link:/tutorial/reading[readings] contains links to resources that cover microservice concepts

=== Guiding Principles
The tutorial is provides guidance throughout the majority of the activities,
but expect's you to actually code and get your head around the concepts presented.

We focus on new ideas and technologies that complement Java EE and
intentionally leave out cloud deployments, continuous integration and other topics that would increase the conceptual overhead and technical complexity of the material.

=== Learning Outcomes
The goal is to learn about common concepts of a microservice architecture,
challenges when migration from a monolith to microservices and practical examples for crafting a solution using WildFly Swarm.

+++
<div class="row">
  <div class="col-md-6">&nbsp;</div>
  <div class="col-md-6">
  <a href="/tutorial/sources" class="btn btn-primary">Source Code<i class="fa fa-chevron-right" aria-hidden="true"></i></a>
  </div>
</div>
+++
