---
title: Announcement 1.0.0.Beta7
publishDate: 2016-04-12
modifyDate: 2016-04-12
author: The WildFly Swarm Team
layout: post.jade
---

=== What's New?

* Some new fractions
  * Hibernate Search
  * JAX-RS Validator
* HTTP endpoints are not reachable until a deployment is complete
* Static content can be updated in a running instance
* Removed our custom JAX-RS exception mapper for `favicon.ico` and replaced it with an Undertow handler
* Numerous fixes for Ribbon, Hystrix and their examples
* Ability to provide a Hystrix Events Stream from your application
* We now publish http://wildfly-swarm.github.io/wildfly-swarm/1.0.0.Beta7/apidocs/index.html[consolidated javadocs]

++++
<!-- more -->
++++

=== `weld` renamed to `cdi`

To clear some naming up we've renamed the `weld` fraction to `cdi`, and as part of that
change `jaxrs-weld` is also now `jaxrs-cdi`.

If you use auto-detection you won't need to change anything, but if you specify
WildFly Swarm dependencies in `pom.xml` you will need to make this change.

=== addAllDependencies() behavior

Previous to this release calling `myArchive.addAllDependencies()` would include the WildFly Swarm dependencies
into WEB-INF/lib, as well as any other Maven dependencies of the project.

Unfortunately that behavior was causing lots of class path problems, so we've now
modified the default behavior such that WildFly Swarm dependencies are no longer
included. It is still possible to replicate the previous behavior, if desired,
by calling `myArchive.addAllDependencies(true)`.

=== Health Endpoints

You can now add health checks to your endpoints!

For instance, we can add the following to a JAX-RS Resource:

[source,java]
----
@Path("/app")
public class HealthCheckResource {

 @GET
 @Path("/diskSpace")
 @Health
 public HealthStatus checkDiskspace() {
    File path = new File(".");
    long freeBytes = path.getFreeSpace();
    long threshold = 1024 * 1024 * 100; // 100mb
    return freeBytes>threshold ?
      HealthStatus.up() :
      HealthStatus.down().withAttribute("freebytes", freeBytes);
 }
}
----

Which is then accessible at http://localhost:8080/health/app/diskSpace.

For further on information on the API, security, etc, please consult https://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/advanced/monitoring.html[the userguide]

=== Project Generator

Thanks to George Gastaldi, we now provide a Web UI for generating Swarm projects on-the-fly! You can generate a Maven project and choose the fractions (if you don't want fractions to be auto-detected) to be added in your build descriptor. Check it out at http://wildfly-swarm.io/generator

=== Changelog

Release notes for 1.0.0.Beta7 are available https://issues.jboss.org/secure/ConfigureReport.jspa?versions=12330156&versions=12329794&versions=12329900&versions=12329901&versions=12329791&versions=12329975&versions=12329902&versions=12329796&versions=12330153&versions=12330152&versions=12329789&versions=12330151&versions=12330076&sections=all&style=html&selectedProjectId=12317020&reportKey=org.jboss.labs.jira.plugin.release-notes-report-plugin%3Areleasenotes&Next=Next[here].

++++
<ul>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-10">SWARM-10</a> ] Combined javadoc for -swarm and config-api</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-121">SWARM-121</a> ] Enable messaging to cluster</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-189">SWARM-189</a> ] HTTP endpoint should not be reachable before deployment is finished</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-230">SWARM-230</a> ] Static content not reloaded on local change when running org.wildfly.swarm.Swarm</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-267">SWARM-267</a> ] Hystrix Metrics Event Stream </li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-297">SWARM-297</a> ] Use ShrinkWrap descriptor for web.xml</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-305">SWARM-305</a> ] Provide RESTful endpoints for common runtime data </li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-321">SWARM-321</a> ] Upgrade to Keycloak 1.9.1.Final</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-327">SWARM-327</a> ] Unable to create an exception mapper for javax.ws.rs.NotFoundException</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-328">SWARM-328</a> ] Hibernate-Search Fraction</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-332">SWARM-332</a> ] addContextParam fails with ClassCastException</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-333">SWARM-333</a> ] System#setProperty fails for swarm.http.port</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-338">SWARM-338</a> ] All fractions should have a wildfly-swarm-bootstrap.conf</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-355">SWARM-355</a> ] Wildfly Swarm Maven Plugin does not use proxy configured in settings.xml</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-358">SWARM-358</a> ] Ribbon archive auto advertise a service by virtue of Maven dependency presence</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-363">SWARM-363</a> ] Ability to specify the name of the deployment archive without a main()</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-366">SWARM-366</a> ] Using Template API with a ResponseValidator in Ribbon Example seems to have classpath problems</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-368">SWARM-368</a> ] Missing resteasy-validator-provider-11 in bom</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-369">SWARM-369</a> ] Add jaxrs-validator fraction</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-373">SWARM-373</a> ] JBoss Modules is unable to find timestamped SNAPSHOT versions</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-374">SWARM-374</a> ] Jackson APIs are not available from jaxrs fraction</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-377">SWARM-377</a> ] -modules dependencies are not being pulled based on BOM versions</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-380">SWARM-380</a> ] Autodetect batch-jberet fraction</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-382">SWARM-382</a> ] mvn install fails when using HttpResponseStatus because class is missing</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-383">SWARM-383</a> ] WARArchive.addAllDependencies() may create invalid libraries</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-384">SWARM-384</a> ] Autodetect mail fraction</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-385">SWARM-385</a> ] Generated JAX-RS application should not take precedence</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-386">SWARM-386</a> ] addAllDependencies() add unncessary libraries</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-388">SWARM-388</a> ] Running a main() in Intellij fails with ClassNotFoundException</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-390">SWARM-390</a> ] Parallel artifact downloads</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-393">SWARM-393</a> ] Adapt the JSON generated in fraction-plugin to contain the necessary info for the generator</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-394">SWARM-394</a> ] mvn wildfly-swarm:run does not destroy the process when executed in an embedded maven environment</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-398">SWARM-398</a> ] Plugin selects older versions of Fractions when using Auto detection</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-399">SWARM-399</a> ] Ability to depend on sun.jdk module without bringing in non JDK Services</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-402">SWARM-402</a> ] Add request-controller subsystem</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-403">SWARM-403</a> ] FractionAnalyzer#detectNeededFractions should return the container fraction only if no other fractions are detected</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-404">SWARM-404</a> ] mvn wildfly-swarm:run should gracefully shutdown when interrupted</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-406">SWARM-406</a> ] Wildfly Swarm plugin does not auto-detect the necessary fractions for javax.json and javax.xml.bind</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-407">SWARM-407</a> ] CNFE for javax/validation/constraints/Size with Swagger</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-408">SWARM-408</a> ] FractionAnalyzer#detectNeededFractions should remove fractions that depend on each other</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-409">SWARM-409</a> ] Move the location of exposed-components.json to a repository root</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-410">SWARM-410</a> ] Rename 'weld' fraction to 'cdi'</li>
  <li>[ <a href="https://issues.jboss.org/browse/SWARM-413">SWARM-413</a> ] JSF fraction detection does not work for subpackages </li>
</ul>
++++


=== Resources

Per usual, we tend to hang out on `irc.freenode.net` in `#wildfly-swarm`.

All bug and feature-tracking is kept in http://issues.jboss.org/browse/SWARM[JIRA].

Examples are available in http://github.com/wildfly-swarm/wildfly-swarm-examples.

Documentation for this release is http://wildfly-swarm.io/documentation/1-0-0-Beta7[available].

=== Thank you, Contributors!

We appreciate all of our contributors since the last release:

*Core*

- Heiko Braun
- Toby Crawley
- Thomas Diesler
- Ken Finnigan
- George Gastaldi
- Bob McWhirter

*Non Core*

- Heiko Braun
- Toby Crawley
- Jim Crossley
- Ken Finnigan
- George Gastaldi
- Bob McWhirter
- Christian Posta
- sassko
- Harald Wellmann

*Examples*

- Heiko Braun
- Ben Browning
- Ken Finnigan
- Bob McWhirter
- Jeff Mesnil

*Documentation*

- Heiko Braun
- Antonino Cucchiara
- Ken Finnigan
- George Gastaldi
- Mark Little
- Bob McWhirter
- Summers Pittman
- Christian Posta
- Harald Wellmann
