---
title: Announcement 1.0.0.CR2
publishDate: 2016-06-20
modifyDate: 2016-06-20
author: The WildFly Swarm Team
layout: post.jade
draft: true
---

== What's New?
* Drools KIE Server
* Vert.x

++++
<!-- more -->
++++

=== Drools KIE Server

Though it's not currently part of the BOM, you can try out the Drools KIE
Server by including the following dependency:

[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>drools-server</artifactId>
  <version>1.0.0.Alpha1</version>
</dependency>
----

and packaging it into a WF Swarm jar to execute!

=== Vert.x

Though it's not currently part of the BOM, you can try out the Vert.x integration by including the following dependency:

[source,xml]
----
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>vertx</artifactId>
  <version>1.0.0.Alpha1</version>
</dependency>
----

The fraction deploys a JCA adapter providing both outbound and inbound connectivy with a Vert.x instance.
An application component (e.g Servlet, EJB), can send messages to a Vert.x instance using the Vert.x EventBus.

Usage:

[source,java]
----
@Resource(mappedName="java:/eis/VertxConnectionFactory")
VertxConnectionFactory connFactory;

public void sendMessage() throws Exception { 
    try (VertxConnection conn = connFactory.getVertxConnection()) {
        conn.vertxEventBus().send("tacos", "Hello from JCA");
    }
}
----

Inbound connectivity is provided via a listener interface which can be implemented by a Java EE Message Driven Bean (MDB). As opposed to the default JMS listener type, the Vert.x JCA listener interface allows an MDB to receive messages from a Vert.x address.

Usage: 

[source,java]
----
package io.vertx.resourceadapter.examples.mdb;

import io.vertx.resourceadapter.inflow.VertxListener;
import io.vertx.core.eventbus.Message;

import java.util.logging.Logger;

import javax.ejb.ActivationConfigProperty;
import javax.ejb.MessageDriven;

import org.jboss.ejb3.annotation.ResourceAdapter;

@MessageDriven(name = "VertxMonitor",
        messageListenerInterface = VertxListener.class,
        activationConfig = {
                @ActivationConfigProperty(propertyName = "address", propertyValue = "tacos")
        }
)
@ResourceAdapter("vertx-ra")
public class VertxMonitor implements VertxListener {

   private static final Logger logger = Logger.getLogger(VertxMonitor.class.getName());

   @Override
   public <String> void onMessage(Message<String> message) {
      logger.info("Get a message from Vert.x at address: " + message.address());
      logger.info("Body of the message: " + message.body());
   }
}
----

See https://github.com/wildfly-swarm/wildfly-swarm-vertx/blob/master/README.md[the vert.x README notes] for more information

== Changelog

Release notes for 1.0.0.CR2 are available https://issues.jboss.org/secure/ConfigureReport.jspa?versions=12329397&versions=12329891&versions=12330676&versions=12330158&versions=12330160&versions=12330161&versions=12330154&versions=12330163&versions=12330162&versions=12330411&versions=12329788&versions=12330164&versions=12329787&versions=12330405&versions=12330155&versions=12330159&versions=12330410&versions=12330404&versions=12329897&sections=all&style=html&selectedProjectId=12317020&reportKey=org.jboss.labs.jira.plugin.release-notes-report-plugin%3Areleasenotes&Next=Next[here].

++++
<ul>
</ul>
++++

== Resources

Per usual, we tend to hang out on `irc.freenode.net` in `#wildfly-swarm`.

All bug and feature-tracking is kept in http://issues.jboss.org/browse/SWARM[JIRA].

Examples are available in https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/1.0.0.CR2.

Documentation for this release is http://wildfly-swarm.io/documentation/1-0-0-CR2[available].

== Thank you, Contributors!

We appreciate all of our contributors since the last release:

*Core*

- emag
- Heiko Braun
- Toby Crawley
- John D. Ament
- Ken Finnigan
- George Gastaldi
- Martin Kouba
- Bob McWhirter

*Non Core*

- Heiko Braun
- Ken Finnigan
- George Gastaldi
- Bob McWhirter

*Examples*

- Ralf Battenfeld
- Heiko Braun
- Thomas Diesler
- Ken Finnigan
- Bob McWhirter
- James Netherton
- Tomas Remes

*Documentation*

- George Gastaldi
- Heiko Braun
- Ken Finnigan
- Toby Crawley
