---
title: Announcing WildFly Swarm 2017.9.0
publishDate: 2017-08-30
modifyDate: 2017-08-30
author: The WildFly Swarm Team
layout: post.jade
draft: true
---

== WildFly Swarm 2017.9.0

[...]

=== What's New?

* Topology.js Changes

++++
<!-- more -->
++++

== Topology.js Changes

*WARNING: Breaking change!*

Previously, the `topology.js` script provided by the `topology-webapp` fraction
exposed a simple `topology()` function that you used like this:

[source,js]
----
var Topology = topology();
... code using Topology ...
----

This was prone to race conditions, because you could start using `Topology` before
the initial topology was obtained from the server.

Code like this will no longer work. The `topology()` function now returns a promise,
which is only resolved when initial topology is obtained from the server. The code
above needs to be transformed to look like this:

[source,js]
----
topology().then(function (Topology) {
    ... code using Topology ...
});
----

Now, you only get the `Topology` object when it is ready to be used.

== Changelog


=== Bug
[...]

== Resources

Per usual, we tend to hang out on `irc.freenode.net` in `#wildfly-swarm`.

All bug and feature-tracking is kept in http://issues.jboss.org/browse/SWARM[JIRA].

Examples are available in https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/2017.8.1

Documentation for this release is available:

* link:/howto/2017-9-0[How To's]
* link:/refguide/2017-9-0[Reference Guide]
* link:/userguide/2017-9-0[User Guide]

== Thank you, Contributors!

We appreciate all of our contributors since the last release:

[...]
