---
title: Announcement 1.0.0.Alpha6
publishDate: 2016-01-18
modifyDate: 2016-01-18
author: The WildFly Swarm Team
layout: post.jade
---

== What is WildFly Swarm?

WildFly Swarm is the decomposition and reconstitution of the popular
WildFly Java Application Server in order to support _just enough app-server_
for microservice type applications.

Each portion of the app-server is referred to as a _fraction_, which many times
maps to a `subsystem` from WildFly, but also may include other discrete chunks
of functionality, such as _Swagger_, _Jolokia_ or _NetflixOSS Ribbon_.

++++
<!-- more -->
++++

== What's New in 1.0.0.Alpha6?

There's quite a bit new stuff in this release, including support for
applications that might want:

* WildFly 10.0.0.CR5 as a base
* `ribbon.js` so your single-page apps can enjoy the benefits of Ribbon-based
  discovery from the browser.
* Swagger
* Java Batch/JBeret support
* WebServices
* WildFly Management API (`jboss-cli` support)

Additionally, we've begun building WildFly Swarm-ified servers which
can either be added as fractions into your own service, or executed
standalone from artifacts that are addressable through Maven coordinates.

Also, we've improved our testing game, both in terms of how WildFly Swarm
itself is tested, and the facilities we provide to make testing your own
applications with WildFly Swarm.

These include changes to the Maven `wildfly-swarm-plugin` to allow

* `wildfly-swarm:start` to start an application for integration-testing
  (used in the `pre-integration-test` Maven lifecycle phase)
* `wildfly-swarm:stop` the opposite of `:start`

== Important Changes

In addition to the new features and bug-fixes, there are some notable changes
that you will need to undertake for your application since 1.0.0.Alpha5.

=== Simplified Maven `artifactId`

In previous versions of WildFly Swarm, all artifacts had a `groupId` of
`org.wildfly.swarm` and an `artifactId` of `wildfly-swarm-something`.

We've simplified the `artifactId` to the bare name of the piece, avoiding
the repetition of `wildfly-swarm-` as a prefix.

For instance, if you had dependencies of:

    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>wildfly-swarm-undertow</artifactId>
    </dependency>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>wildfly-swarm-weld</artifactId>
    </dependency>

starting with 1.0.0.Alpha6, they should be simplified to:

    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>undertow</artifactId>
    </dependency>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>weld</artifactId>
    </dependency>

=== Renamed Properties

In the name of consistency, we've adjusted the names of the system
properties we use. Before, we had a mix of `jboss.\*`, `swarm.*`, and
`wildfly.swarm.\*` properties - those now are all `swarm.*` properties, and,
in one case, the property was made less verbose.

Public properties that have changed are:

[cols=2, options="header"]
|===
|Old
|New

|wildfly.swarm.context.path
|swarm.context.path

|wildfly.swarm.environment
|swarm.environment

|wildfly.swarm.ribbon.context.path
|swarm.ribbon.context.path

|jboss.bind.address
|swarm.bind.address

|jboss.http.port
|swarm.http.port

|jboss.https.port
|swarm.https.port

|jboss.socket.binding.port-offset
|swarm.port.offset

|jboss.default.multicast.address
|swarm.default.multicast.address

|jboss.management.http.port
|swarm.management.http.port

|jboss.management.https.port
|swarm.management.https.port

|===

So if you were using any of the old properties, you'll need to adjust
accordingly.

=== Changelog

Release notes for 1.0.0.Alpha6 are available https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12317020&version=12329354[here].

As a result of our move from GitHub issues to JIRA, some issues that are marked as part of the 1.0.0.Alpha6 release were actually part of prior releases. Apologies for any confusion that may cause when viewing the Release notes.

=== Resources

Per usual, we tend to hang out on `irc.freenode.net` in `#wildfly-swarm`.

We've moved all bug and feature-tracking to http://issues.jboss.org/browse/SWARM[JIRA].

Examples are available in http://github.com/wildfly-swarm/wildfly-swarm-examples.

Documentation for this release is http://wildfly-swarm.io/documentation/1-0-0-Alpha6[available].

=== Thank you, Contributors!

We appreciate all of our contributors since the last release:

*Core*

* Ben Browning
* Ben Tomasini
* Bernard Tison
* Bob McWhirter
* James Perkins
* John D. Ament
* Ken Finnigan
* Lance Ball
* Paris Apostolopoulos
* Thomas Meyer
* Toby Crawley
* Yoshimasa Tanabe
* John Clingan
* John Hovell

*Examples*

* Heiko Braun
* Ben Browning
* Bob McWhirter
* Ken Finnigan
* Kylin Soong
* Lance Ball
* Mark Little
* Toby Crawley
* William Antônio Siqueira
* Yoshimasa Tanabe
* Helio Frota

*Documentation*

* Bob McWhirter
* James Perkins
* Lance Ball
* Toby Crawley

*Random other Thanks*

* John Mazzitelli (Hawkular)
* Peter Palaga (Hawkular)
* Stian Thorgersen (Keycloak)
* David M. Lloyd (JBoss Modules)
* Tomaz Cerar (WildFly)
* Roland Huß (Docker/Maven)
* Stuart Douglas (Infinispan)
* Paul Ferraro (Infinispan)
* Bruno Georges (Boss, Presentations)
* Lance Ball (Presentations)
* Andrew L. Rubinger (Shrinkwrap/Arquillian)
* Aslak Knutsen (Shrinkwrap)
* Ralf Battenfeld (Shrinkwrap Descriptors)
