---
title: Rightsize your JavaEE Applications
layout: index.jade
---

++++
<section class="section">
<div class="container">

<p>
Swarm offers an innovative approach to packaging and running JavaEE applications by packaging them with just enough of the
server runtime to "java -jar" your application. However, it's all much, much cooler than that ...
</p>

</div>
</section>
++++

[pass]
++++
<section class="section alt">
<div class="container">

<div class="row">
  <div class="col-md-6">
    <div class="page-header">
    <h2>Example</h2>
    </div>
++++

Using WildFly swarm is easy! Add dependencies for just the parts of WildFly that you need 
(or don't add anything at all and the plugin will auto-detect for you). 
The following example assumes a simple JAX-RS RESTful application.

[source,xml]
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>jaxrs</artifactId>
</dependency>

To create an uberjar, configure the plugin:

[source,xml]
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  <executions>
    <execution>
      <goals>
        <goal>package</goal>
      </goals>
    </execution>
  </executions>
</plugin>

Deploy the generated .war to any JavaEE compatible application server, or run the uberjar:
[source, bash]
java -jar MyApp-swarm.jar

[pass]
++++
<p style="margin-bottom:50px">
<a href="https://github.com/wildfly-swarm/wildfly-swarm-examples" class="btn btn-primary">View Examples</a>
</p>

  </div>

  <div class="col-md-6">
    <div class="page-header">
    <h2>Getting Started</h2>
    </div>
    <h3>Generate Project</h3>
    <p>The most simple way to get started is using the project generator.
    Simply chose the capabilities you need and we generate a maven project for you, ready to download and use.
    </p>
    <p><a href="/generator" class="btn btn-primary">Create a Project</a></p>

    <h3>Documentation</h3>
    <p>The userguide contains much information to get started and to answer more advanced questions.
    <p><a href="/documentation/HEAD" class="btn btn-primary">View Documentation</a></p>

  </div>

  </div>
</div>
</section>
++++

[pass]
++++
<section class="section">
<div class="container">
<div class="page-header">
  <h2>Features and Benefits</h2>
</div>
<div class="row">
  <div class="col-md-4">
  <div class="well">
  <p>
    <h3><i class="fa fa-industry"></i> Mature</h3>
    Develop services using the feature richness and maturity of the enterprise Java industry standard - JavaEE
    </p>
  </div>
  </div>
  <div class="col-md-4">
  <div class="well">
  <p>
    <h3><i class="fa fa-cubes"></i> Flexible</h3>
    Simply specify WildFly Swarm maven dependencies to bundle just the parts of the JavaEE 7 WildFly application server
    that you need. Don't use EJBs or JPA? Great, nothing is bundled unless you specify it!
    </p>
  </div>
  </div>

  <div class="col-md-4">
  <div class="well">
    <p>
    <h3><i class="fa fa-check"></i> Straightforward</h3>
      Generate uberjar (Ex: java -jar MyApp.jar), or generate a .war and deploy to any JavaEE compatible application server.
    </p>
  </div>
  </div>

</div>
<div class="row">
  <div class="col-md-4">
    <div class="well">
    <h3><i class="fa fa-sitemap"></i> Service Oriented</h3>
    Use built-in service discovery, or use external service registries. You choose.
    </div>
  </div>
  <div class="col-md-4">
    <div class="well">
    <h3><i class="fa fa-wrench"></i> Practical</h3>
    Built-in support for third party apps and frameworks like Logstash and NetFlix OSS projects like Hystrix and Ribbon.
    </div>
  </div>
  <div class="col-md-4">
    <div class="well">
    <h3><i class="fa fa-puzzle-piece"></i> Integrated</h3>
    Integrates with upstream Red Hat projects for single sign-on <a href="http://keycloak.jboss.org/">KeyCloak</a>,
    monitoring <a href="http://www.hawkular.org/">Hawkular</a>, data grid <a href="http://www.infinispan.org">InfiniSpan</a>, and more
    broadly, Platform as a Service <a href="https://www.openshift.com/">OpenShift</a>.
    </div>
  </div>
</div>
</div>
</section>
++++
